spring.application.name=springDataRest
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Rustam02071989!
spring.servlet.encoding.charset=UTF-8
spring.http.converters.string-encoding-charset=UTF-8
server.port=8080
management.endpoints.web.exposure.include=health,info,beans,mappings
management.info.env.enabled=true
info.app.name = REST API Spring Boot TEST
info.app.description =Данное приложение создавалось в Spring boot  для Rest  итз коробки \
  для таблицы Employees в PostgreSQL
info.app.autor  = Osmanov Rustam
spring.security.user.name=Rustam
spring.security.user.password=Rustam
